name: Namecheap Production Deployment
run-name: ${{ github.actor }} is automated deploying to Namecheap ðŸš€

on:
  push:
    branches: [server-production]

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: ðŸ”¨ Build backend project
        run: |
          cd backend
          npm install
          npm test
      - name: ðŸ”¨ Build frontend project
        run: |
          cd frontend
          npm install
          npm run build --if-present
          npm test

      - name: ðŸ“‚ Deploying backend to Namecheap
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_BACKEND_USERNAME }}
          password: ${{ secrets.FTP_BACKEND_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL }}
          local-dir: ./backend/
      - name: ðŸ“‚ Deploying frontend to Namecheap
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_FRONTEND_USERNAME }}
          password: ${{ secrets.FTP_FRONTEND_PASSWORD }}
          protocol: ${{ secrets.FTP_PROTOCOL }}
          local-dir: ./frontend/build/
